# Basic
title: Yi Qin
subtitle: Personal Website
description: Welcome to my personal website~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Yi Qin
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Machine Learning
url: "https://QinYi-team.github.io"

# Comment
comment:
    #disqus: leopard
    # gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    #QQ:
    github: QinYi-team
    # zhihu: panpanleopard
    # juejin: xxx
    #ianshu: 2ada30d8d0f7
    # twitter:
    mail: qy_808@aliyun.com


# ç™¾åº¦ç»Ÿè®¡
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
baidu:
    id: 23b1d79cb018f5a9f3f87787aaea21ef



# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Personal Homepage

# Navigation buttons in the front page.s
nav:
    - {title: Introduction and Code, description: archive, url: '/archive'}
   # - {title: Tag, description: tags, url: '/tags'}
    - {title: About Me, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
